Mollie: Only update status if we are in the default order status
tastyigniter/ti-ext-payregister pull request #13
Opened 2020-10-16 10:27 UTC by ryanmitchell

2020-10-16 22:56 UTC, sampoyigi requested changes

2020-10-16 22:56 UTC, sampoyigi commented on payments/Mollie.php
> +        if ($order->status_id == setting('default_order_status', 1))
`!$order->isPaymentProcessed()` would work here.

2020-10-17 08:05 UTC, ryanmitchell commented on payments/Mollie.php
> +        if ($order->status_id == setting('default_order_status', 1))
Ok - updated

2020-10-25 11:07 UTC, merged

2020-10-26 20:19 UTC, BlueRayNL commented on payments/Mollie.php
> +        if ($order->status_id == setting('default_order_status', 1))
Hi,

I implemented the fiks however. need to wait for a customer to test it.
i will get back it tomorrow :)