Update process.square.js to use the WebPayments SDK instead of SqPaymentForm
tastyigniter/ti-ext-payregister pull request #31
Opened 2021-09-07 23:17 UTC by CupNoodles

Deprecation warning no longer shows up in the web console. 

I've only tested in sandbox, but can confirm that behaviors are the same between the old SqPaymentForms implementation and this one. I've 'tested' the SCA process in sandbox with the values described in https://developer.squareup.com/docs/testing/test-values, but as I don't have an EU bank account I have no clue what this looks like in production.

2021-09-08 16:25 UTC, sampoyigi requested changes

2021-09-08 16:25 UTC, sampoyigi commented on assets/process.square.js
> +        this.card = await payments.card({
Move this has to ProcessSquare.DEFAULTS

2021-09-08 16:26 UTC, sampoyigi commented
Apart from the requested changes, everything else appears to be in order, and I'll come back later to further check and test it. Thank you for your time and work!

2021-09-08 16:56 UTC, CupNoodles commented
Moved the card styles over! Should I be trying to fix these CI failures?

2021-09-08 19:28 UTC, sampoyigi commented
Yup

2021-09-28 07:25 UTC, sampoyigi commented
Thank you for your efforts; apart from a typo with the verificationToken, I was able to test without issue.

2021-09-28 07:25 UTC, merged